### ISSUE TITLE
执行./garmin2suunto一直没有反应

### ISSUE THREAD

**Issue by wuy069** [yqt/go-garmin2suunto#1]
按照您的Usage，编译后，执行./garmin2suunto一直没有反应，在联网的linux图形界面终端执行也是同样没有反应，请问如何使用。能否在Readme里写具体点，谢谢！

**Comment by yqt** [comment]
说明已更新。

同步设置有需要的话可以修改：[link](https://github.com/yqt/go-garmin2suunto/blob/ca35d99e208997d73daf6c42eff3f7e799ffba6c/sync/sync.go#L36)。

我个人是对接telegram bot按需手动触发同步的，频繁同步可能不太安全，可以参考。

**Comment by wuy069** [comment]
按您写的操作后还是没起作用。
我先在config.go里填上我的佳明账号和密码，再填上Suunto账号，SuuntoUserKey  = "f22830ec-359f-4d6b-9574-5bc269a70ccf"，保存后，再进入main文件夹执行CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-s -w' -o garmin2suunto
编译生成可执行go程序garmin2suunto，这时终端执行PORT=38080 ./garmin2suunto，然后就停在这了。我这时打开http://www.movescount.cn/zh/settings#connections并没有在允许的应用中找到garmin2suunto或go-garmin2suunto.
后来我查看garmin/client.go里面用的connect.garmin.com和https://sso.garmin.com的com改为cn了，您可能用的佳明国际账号，我用的国内大陆账号。改后重新编译，但结果还是一样的，不知道哪里出问题了。

**Comment by yqt** [comment]
国内账号可以看看[garmin2suunto](https://github.com/goodtools/garmin2suunto) 这个项目是怎么处理的。
或者通过浏览器自行分析登陆部分的网页请求。

**Comment by wuy069** [comment]
不好意思，才看到消息。非常感谢您的回复！我看这些是想把自己的garmin跑表数据和keep连接同步。现在keep已经正式支持Garmin跑步数据的同步了，我这几天用了还不错。
再次感谢！

祝好！
Yong Wu

hackaday ***@***.***> 于2021年3月22日周一 上午11:38写道：
